version: '3.4'

services:

    support_ms:
        build:
            context: .
            dockerfile: dockerfile
        image: crowstream_support_ms
        container_name: crowstream_support_ms
        env_file: .env
        ports:
            - '3000:3000'
        volumes:
            - .:/urs/src/app

    support_db:
        image: mongo:4.4.10
        container_name: crowstream_support_db
        environment:
            - MONGO_INITDB_ROOT_USERNAME=${SUPPORT_DB_USER}
            - MONGO_INITDB_ROOT_PASSWORD=${SUPPORT_DB_PASSWORD}
        ports:
            - '27017:27017'
        volumes:
            - support_data:/data/db

    mongo-express:
        image: mongo-express
        restart: always
        container_name: crowstream_mongo_express
        environment:
            - ME_CONFIG_MONGODB_ADMINUSERNAME=${SUPPORT_DB_USER}
            - ME_CONFIG_MONGODB_ADMINPASSWORD=${SUPPORT_DB_PASSWORD}
            - ME_CONFIG_MONGODB_URL=${SUPPORT_DB_URL}
            - ME_CONFIG_OPTIONS_EDITORTHEME=ambiance
        depends_on:
            - support_db
        ports:
            - '8081:8081'

volumes:
    support_data: null
