version: '3.4'

services:

    crowstream_mq:
        image: rabbitmq:3.8-management-alpine
        container_name: 'crowstream_rabbitmq'
        ports:
            - 5672:5672
            - 15672:15672
        networks:
            - crowstream_rabbitmq
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:15672"]
            interval: 30s
            timeout: 10s
            retries: 5

    support_ms:
        build:
            context: .
            dockerfile: dockerfile
        image: crowstream_support_ms
        container_name: crowstream_support_ms
        depends_on:
          - crowstream_mq
        env_file: .env
        ports:
            - '3000:3000'
        volumes:
            - .:/urs/src/app
        networks:
          - crowstream_rabbitmq

    support_db:
        image: mongo:4.4.10
        container_name: crowstream_support_db
        environment:
            - MONGO_INITDB_ROOT_USERNAME=${SUPPORT_DB_USER}
            - MONGO_INITDB_ROOT_PASSWORD=${SUPPORT_DB_PASSWORD}
        ports:
            - '27017:27017'
        volumes:
            - support_data:/data/db
        networks:
          - crowstream_rabbitmq
        
    mongo-express:
        image: mongo-express
        restart: always
        container_name: crowstream_mongo_express
        environment:
            - ME_CONFIG_MONGODB_ADMINUSERNAME=${SUPPORT_DB_USER}
            - ME_CONFIG_MONGODB_ADMINPASSWORD=${SUPPORT_DB_PASSWORD}
            - ME_CONFIG_MONGODB_URL=${SUPPORT_DB_URL}
            - ME_CONFIG_OPTIONS_EDITORTHEME=ambiance
        depends_on:
            - support_db
        ports:
            - '8081:8081'
        networks:
          - crowstream_rabbitmq

volumes:
    support_data: null


networks:
  crowstream_rabbitmq:
    driver: bridge
