version: '3.4'

services:

    express-api:
      build:
        context: .
        dockerfile: dockerfile
      image: express-api 
      env_file: .env
      ports: 
        - '3000:3000'
      volumes:
        - .:/urs/src/app

    mongo:
        image: mongo:4.4.10
        environment:
            - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USER}
            - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
        ports:
            - '27017:27017'
        volumes:
            - data:/data/db

    mongo-express:
        image: mongo-express
        restart: always
        environment:
            - ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGO_ROOT_USER}
            - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGO_ROOT_PASSWORD}
            - ME_CONFIG_MONGODB_URL=${MONGO_ROOT_URL}
        depends_on:
            - mongo
        ports:
          - '8081:8081'

volumes:
    data: 